services:
# NGINX Proxy Manager with LetsEncrypt https://github.com/jc21/nginx-proxy-manager
  proxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxymanager
    labels:
      - "com.dockstarter.appinfo.description: NGINX Proxy Manager with LetsEncrypt included"
      - "com.dockstarter.appinfo.nicename: NGINX Proxy Manager"
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - FORCE_COLOR=1
      - NODE_ENV=config
    volumes:
      - ${DOCKERCONFDIR}/proxymanager/config:/app/config/
      - ${DOCKERCONFDIR}/proxymanager/data:/data
      - ${DOCKERCONFDIR}/proxymanager/letsencrypt:/etc/letsencrypt
      - ${DOCKERSHAREDDIR}:/shared
    depends_on:
      - mariadb
    restart: unless-stopped
# MariaDB for use with NGINX Proxy Manager https://github.com/linuxserver/docker-mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    labels:
      - "com.dockstarter.appinfo.description: MariaDB for NGINX Proxy Manager"
      - "com.dockstarter.appinfo.nicename: DB NGINX Proxy Manager"
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dockstarter
      - MYSQL_DATABASE=proxymgr
      - MYSQL_USER=dockstarter
      - MYSQL_PASSWORD=dockstarter
      - FORCE_COLOR=1
    volumes:
      - ${DOCKERCONFDIR}/mariadb:/var/lib/mysql
      - ${DOCKERSHAREDDIR}:/shared
    restart: unless-stopped